name: STEP 2 - CNC ISPO OFFICIAL

on: 
  workflow_dispatch: # Trigger the workflow manually

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository # Step to check out the repository
      uses: actions/checkout@v2

    - name: Run script # Step to run the python script
      run: python extract_poolId.py CNC_Active_ISPO_POOL_CHECK.json

    - name: Upload JSON file # Step to upload the generated JSON file
      run: |
        git add CNC_Alliance.json
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Uploaded CNC_Alliance.json"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Push Changes
      run: git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
